#!/bin/bash

# default install
yum update -y
amazon-linux-extras install emacs nginx1.12 -y
yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
yum install python2-certbot-nginx -y

# tweak nginx
mkdir -p /etc/nginx/sites-available
mkdir -p /etc/nginx/sites-enabled
mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

echo -e dXNlciBuZ2lueDsKd29ya2VyX3Byb2Nlc3NlcyBhdXRvOwplcnJvcl9sb2cgL3Zhci9sb2cvbmdpbngvZXJyb3IubG9nOwpwaWQgL3J1bi9uZ2lueC5waWQ7CgppbmNsdWRlIC91c3Ivc2hhcmUvbmdpbngvbW9kdWxlcy8qLmNvbmY7CgpldmVudHMgewogICAgd29ya2VyX2Nvbm5lY3Rpb25zIDEwMjQ7Cn0KCmh0dHAgewogICAgbG9nX2Zvcm1hdCAgbWFpbiAgJyRyZW1vdGVfYWRkciAtICRyZW1vdGVfdXNlciBbJHRpbWVfbG9jYWxdICIkcmVxdWVzdCIgJwogICAgICAgICAgICAgICAgICAgICAgJyRzdGF0dXMgJGJvZHlfYnl0ZXNfc2VudCAiJGh0dHBfcmVmZXJlciIgJwogICAgICAgICAgICAgICAgICAgICAgJyIkaHR0cF91c2VyX2FnZW50IiAiJGh0dHBfeF9mb3J3YXJkZWRfZm9yIic7CgogICAgYWNjZXNzX2xvZyAgL3Zhci9sb2cvbmdpbngvYWNjZXNzLmxvZyAgbWFpbjsKCiAgICBzZW5kZmlsZSAgICAgICAgICAgIG9uOwogICAgdGNwX25vcHVzaCAgICAgICAgICBvbjsKICAgIHRjcF9ub2RlbGF5ICAgICAgICAgb247CiAgICBrZWVwYWxpdmVfdGltZW91dCAgIDY1OwogICAgdHlwZXNfaGFzaF9tYXhfc2l6ZSAyMDQ4OwoKICAgIGluY2x1ZGUgICAgICAgICAgICAgL2V0Yy9uZ2lueC9taW1lLnR5cGVzOwogICAgZGVmYXVsdF90eXBlICAgICAgICBhcHBsaWNhdGlvbi9vY3RldC1zdHJlYW07CgogICAgaW5jbHVkZSAvZXRjL25naW54L2NvbmYuZC8qLmNvbmY7CgogICAgIyMjIGtwcGluZyBhZGRlZAogICAgc2VydmVyX3Rva2VucyAgIG9mZjsKICAgIGFkZF9oZWFkZXIgICAgICBYLUNvbnRlbnQtVHlwZS1PcHRpb25zIG5vc25pZmY7CiAgICBhZGRfaGVhZGVyICAgICAgWC1YU1MtUHJvdGVjdGlvbiAiMTsgbW9kZT1ibG9jayI7CiAgICBhZGRfaGVhZGVyICAgICAgWC1GcmFtZS1PcHRpb25zIFNBTUVPUklHSU47CgogICAgc3NsX3Nlc3Npb25fY2FjaGUgICAgICAgICBzaGFyZWQ6U1NMOjEwbTsKICAgIHNzbF9zZXNzaW9uX3RpbWVvdXQgICAgICAgMTBtOwogICAgc3NsX3ByZWZlcl9zZXJ2ZXJfY2lwaGVycyBvbjsKICAgIHNzbF9wcm90b2NvbHMgICAgICAgICAgICAgVExTdjEgVExTdjEuMSBUTFN2MS4yOwogICAgc3NsX2NpcGhlcnMgICAgICAgICAgICAgICAiRUVDREgrQUVTR0NNOkVESCtBRVNHQ006QUVTMjU2K0VFQ0RIOkFFUzI1NitFREgiOwogICAgYWRkX2hlYWRlciAgICAgICAgICAgICAgICBTdHJpY3QtVHJhbnNwb3J0LVNlY3VyaXR5ICdtYXgtYWdlPTYzMDcyMDAwOyBpbmNsdWRlU3ViRG9tYWluczsgcHJlbG9hZCcgYWx3YXlzOwoKICAgIGd6aXAgICAgICAgICAgICAgICAgb247CiAgICBnemlwX2h0dHBfdmVyc2lvbiAgIDEuMDsKICAgIGd6aXBfbWluX2xlbmd0aCAgICAgMTEwMDsKICAgIGd6aXBfYnVmZmVycyAgICAgICAgNCA4azsKICAgIGd6aXBfdHlwZXMKICAgICAgICBhcHBsaWNhdGlvbi9hdG9tK3htbAogICAgICAgIGFwcGxpY2F0aW9uL2phdmFzY3JpcHQKICAgICAgICBhcHBsaWNhdGlvbi9qc29uCiAgICAgICAgYXBwbGljYXRpb24vcnNzK3htbAogICAgICAgIGFwcGxpY2F0aW9uL3htbAogICAgICAgIGZvbnQvb3BlbnR5cGUKICAgICAgICBmb250L3RydWV0eXBlCiAgICAgICAgaW1hZ2Uvc3ZnK3htbAogICAgICAgIHRleHQvY3NzCiAgICAgICAgIyB0ZXh0L2h0bWwgaXMgYWx3YXlzIGNvbXByZXNzZWQgYnkgSHR0cEd6aXBNb2R1bGUKICAgICAgICB0ZXh0L3BsYWluCiAgICAgICAgdGV4dC94bWw7CiAgICBnemlwX3Byb3hpZWQgICAgICAgIGV4cGlyZWQgbm8tY2FjaGUgbm8tc3RvcmUgcHJpdmF0ZSBhdXRoOwogICAgZ3ppcF9kaXNhYmxlICAgICAgICAibXNpZTYiOwogICAgZ3ppcF92YXJ5ICAgICAgICAgICBvbjsKICAgIGd6aXBfY29tcF9sZXZlbCAgICAgNjsKCiAgICBpbmNsdWRlIC9ldGMvbmdpbngvc2l0ZXMtZW5hYmxlZC8qOwogICAgIyMjCn0K | base64 --decode > /etc/nginx/nginx.conf

echo -e c2VydmVyIHsKICAgIGxpc3RlbiAgICAgICA4MCBkZWZhdWx0X3NlcnZlcjsKICAgIGxpc3RlbiAgICAgICBbOjpdOjgwIGRlZmF1bHRfc2VydmVyOwogICAgc2VydmVyX25hbWUgIF87CiAgICByb290ICAgICAgICAgL3Vzci9zaGFyZS9uZ2lueC9odG1sOwoKICAgIGluY2x1ZGUgL2V0Yy9uZ2lueC9kZWZhdWx0LmQvKi5jb25mOwoKICAgIGxvY2F0aW9uIC8gewogICAgfQoKICAgIGVycm9yX3BhZ2UgNDA0IC80MDQuaHRtbDsKICAgICAgICBsb2NhdGlvbiA9IC80MHguaHRtbCB7CiAgICB9CgogICAgZXJyb3JfcGFnZSA1MDAgNTAyIDUwMyA1MDQgLzUweC5odG1sOwogICAgICAgIGxvY2F0aW9uID0gLzUweC5odG1sIHsKICAgIH0KfQo= | base64 --decode > /etc/nginx/sites-available/default.conf

ln -s /etc/nginx/sites-available/default.conf /etc/nginx/sites-enabled/default.conf

systemctl start nginx
systemctl enable nginx
